# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#858585"
  hr_color: "#A4D8FA"

# html lang
# ---------------
language: en

# Main menu navigation
# ---------------
menu:
  Blog: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  #XXX: /xxx

# Favicon
# ---------------
favicon: /favicon.ico

# PWA
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#1B9EF3"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg


# Highlight theme
# ---------------
highlight_theme: default

# code_word_wrap: true or false

# Nav settings
# ---------------
social:
  github: https://github.com/crystalynliu
  weibo: https://www.weibo.com/1362052552/profile?topnav=1&wvr=6&is_all=1
  facebook-official: https://www.facebook.com/liu.xinqian

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: false
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

# MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# Analysis
# ---------------
baidu_analytics: 

google_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: 

top_img: true # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

wordcount:
  enable: true

toc:
  enable: true
  #  number: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
# auto_excerpt:
#   enable: false
#   length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: false
  #pubid: 

# sharejs:
  # enable: false
  # disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: true 
  shortname: crystalynliu
  count: true

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

# Footer Settings
# ---------------
since: 2018

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
#links_title: Links
#links:
  #Name: url
